---
- name: Configure multi-homed firewall with reverse proxy
  hosts: all
  become: yes
  vars:
    wg0_conf: ""
    lab_network: "10.20.0.0/24"
    lab_gateway_ip: "10.20.0.1"
    openrelik_ip: "10.20.0.30"
    remnux_ip: "10.20.0.20"
    enable_guacamole: true
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install packages for firewall and reverse proxy
      apt:
        name:
          - curl
          - jq
          - wireguard
          - nftables
          - resolvconf
          - nginx
          - tcpdump
          - tshark
          - suricata
        state: present

    - name: Install Docker for Guacamole (optional)
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
      when: enable_guacamole

    - name: Set iptables to legacy mode for Docker compatibility
      alternatives:
        name: "{{ item }}"
        path: "/usr/sbin/{{ item }}-legacy"
      loop:
        - iptables
        - ip6tables
      when: enable_guacamole

    - name: Restart Docker after iptables change
      systemd:
        name: docker
        state: restarted
      when: enable_guacamole

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Write WireGuard configuration if provided
      copy:
        dest: /etc/wireguard/wg0.conf
        content: "{{ wg0_conf }}"
        mode: '0600'
      when: wg0_conf | length > 0

    - name: Ensure wg-quick service is enabled
      systemd:
        name: wg-quick@wg0
        enabled: yes
      when: wg0_conf | length > 0

    - name: Bring up wg0 interface
      command: wg-quick up wg0
      register: wg_up_result
      changed_when: wg_up_result.rc == 0
      failed_when: false
      when: wg0_conf | length > 0

    - name: Wait for WireGuard interface to be ready
      wait_for:
        timeout: 5
      when: wg0_conf | length > 0

    - name: Verify Mullvad tunnel is active
      shell: |
        set -e
        # Check if wg0 interface exists
        ip addr show wg0 | grep -q inet || exit 1
        
        # Check if we have a WireGuard peer configured
        wg show wg0 | grep -q peer || exit 1
        
        # Test connectivity through tunnel
        timeout 10 curl -s --interface wg0 https://am.i.mullvad.net/json | jq -e '.mullvad_exit_ip' > /dev/null || exit 1
        
        echo "Mullvad tunnel verified and operational"
      register: mullvad_check
      failed_when: false
      changed_when: false
      when: wg0_conf | length > 0

    - name: Display Mullvad status
      debug:
        msg:
          - "Mullvad Tunnel Status: {{ 'ACTIVE ✓' if mullvad_check.rc == 0 else 'INACTIVE ✗' }}"
          - "{{ mullvad_check.stdout if mullvad_check.rc == 0 else 'WARNING: Mullvad tunnel not verified. Lab traffic may not egress properly!' }}"
      when: wg0_conf | length > 0

    - name: Warn if Mullvad not configured
      debug:
        msg:
          - "⚠️  WARNING: No Mullvad WireGuard configuration provided!"
          - "Lab VMs will NOT have internet access until you configure wg0."
          - "Set MULLVAD_WG_CONF environment variable and reprovision."
      when: wg0_conf | length == 0

    - name: Check if WireGuard config exists
      stat:
        path: /etc/wireguard/wg0.conf
      register: wg_conf_stat

    - name: Configure nftables for multi-homed firewall
      copy:
        dest: /etc/nftables.conf
        mode: '0644'
        content: |
          #!/usr/sbin/nft -f
          # nftables rules for multi-homed lab firewall
          flush ruleset
          
          table inet filter {
            chain input {
              type filter hook input priority 0; policy drop;
              ct state established,related accept
              ct state invalid drop
              iif "lo" accept
              
              # Allow SSH only from host network (not exposed externally)
              # Vagrant-libvirt default network is typically 192.168.121.0/24
              iif "eth0" ip saddr 192.168.121.0/24 tcp dport 22 accept
              
              # Allow HTTP/HTTPS from public interface (for reverse proxy)
              # Expose OpenRelik (8710/8711) and Guacamole (18080)
              iif "eth0" tcp dport { 80, 443, 8710, 8711, 18080 } accept
              
              # Allow lab network to access firewall services
              ip saddr {{ lab_network }} accept
            }
            
            chain forward {
              type filter hook forward priority 0; policy drop;
              ct state established,related accept
              ct state invalid drop
              
              # Log DNS queries from lab network (for malware C2 analysis)
              ip saddr {{ lab_network }} udp dport 53 log prefix "LAB_DNS: " level info
              ip saddr {{ lab_network }} tcp dport 53 log prefix "LAB_DNS_TCP: " level info
              
              {% if wg_conf_stat.stat.exists %}
              # Lab network can only egress via WireGuard
              ip saddr {{ lab_network }} oifname "wg0" accept
              
              # Allow return traffic from wg0 to lab
              iif "wg0" ip daddr {{ lab_network }} accept
              {% else %}
              # Fallback: allow lab egress via eth0 when WireGuard is not configured
              ip saddr {{ lab_network }} oifname "eth0" accept
              
              # Allow return traffic from eth0 to lab
              iif "eth0" ip daddr {{ lab_network }} accept
              {% endif %}
              
              # NO direct forwarding between interfaces beyond defined egress
            }
            
            chain output {
              type filter hook output priority 0; policy accept;
            }
          }
          
          table inet nat {
            chain postrouting {
              type nat hook postrouting priority 100; policy accept;
              {% if wg_conf_stat.stat.exists %}
              # NAT lab traffic going out via WireGuard
              ip saddr {{ lab_network }} oifname "wg0" masquerade
              {% else %}
              # NAT lab traffic out the public interface when WireGuard is not configured
              ip saddr {{ lab_network }} oifname "eth0" masquerade
              {% endif %}
            }
          }
      notify: Reload nftables

    - name: Configure nginx reverse proxy for lab services
      copy:
        dest: /etc/nginx/sites-available/lab-proxy
        mode: '0644'
        content: |
          # Main Landing Page (port 80)
          server {
            listen 80 default_server;
            server_name _;
            
            root /vagrant/services;
            index index.html;
            
            location / {
              try_files $uri $uri/ =404;
            }
            
            error_page 404 /index.html;
          }

          # Neko Tor Browser UI (port 8080)
          server {
            listen 8080;
            server_name _;

            location / {
              proxy_pass http://{{ neko_ip }}:8080;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }

          # Neko Chromium UI (port 8090)
          server {
            listen 8090;
            server_name _;

            location / {
              proxy_pass http://{{ neko_ip }}:8090;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
          
          # OpenRelik API (port 8710)
          server {
            listen 8710;
            server_name _;
            
            location / {
              proxy_pass http://{{ openrelik_ip }}:8710;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
          
          # OpenRelik UI (port 8711)
          server {
            listen 8711;
            server_name _;
            
            location / {
              proxy_pass http://{{ openrelik_ip }}:8711;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
          
          # Guacamole Web Gateway (port 18080)
          server {
            listen 18080;
            server_name _;
            
            location /guacamole/ {
              proxy_pass http://127.0.0.1:8082/guacamole/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
      notify: Restart nginx

    - name: Configure nginx main configuration (no RDP stream)
      copy:
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        content: |
          user www-data;
          worker_processes auto;
          pid /run/nginx.pid;
          include /etc/nginx/modules-enabled/*.conf;
          
          events {
            worker_connections 768;
          }
          
          http {
            sendfile on;
            tcp_nopush on;
            tcp_nodelay on;
            keepalive_timeout 65;
            types_hash_max_size 2048;
            
            include /etc/nginx/mime.types;
            default_type application/octet-stream;
            
            access_log /var/log/nginx/access.log;
            error_log /var/log/nginx/error.log;
            
            gzip on;
            include /etc/nginx/sites-enabled/*;
          }
      notify: Restart nginx

    - name: Enable nginx reverse proxy site
      file:
        src: /etc/nginx/sites-available/lab-proxy
        dest: /etc/nginx/sites-enabled/lab-proxy
        state: link
      notify: Restart nginx

    - name: Remove nginx default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart nginx

    - name: Create packet capture directory
      file:
        path: /var/log/pcaps
        state: directory
        mode: '0755'

    - name: Create continuous packet capture script
      copy:
        dest: /usr/local/bin/lab-pcap-capture
        mode: '0755'
        content: |
          #!/bin/bash
          # Continuous packet capture of lab network traffic
          PCAP_DIR="/var/log/pcaps"
          MAX_SIZE_MB=100
          ROTATE_MINUTES=60
          
          mkdir -p "$PCAP_DIR"
          
          # Capture lab interface traffic (eth1)
          exec tcpdump -i eth1 \
            -w "$PCAP_DIR/lab-$(date +%Y%m%d-%H%M%S).pcap" \
            -G $((ROTATE_MINUTES * 60)) \
            -C "$MAX_SIZE_MB" \
            -Z root \
            -z gzip \
            not port 22

    - name: Create systemd service for packet capture
      copy:
        dest: /etc/systemd/system/lab-pcap.service
        mode: '0644'
        content: |
          [Unit]
          Description=Lab Network Packet Capture
          After=network.target
          
          [Service]
          Type=simple
          ExecStart=/usr/local/bin/lab-pcap-capture
          Restart=always
          RestartSec=5
          
          [Install]
          WantedBy=multi-user.target

    - name: Enable and start packet capture service
      systemd:
        name: lab-pcap
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Configure log rotation for pcaps
      copy:
        dest: /etc/logrotate.d/lab-pcaps
        mode: '0644'
        content: |
          /var/log/pcaps/*.pcap.gz {
            daily
            rotate 7
            maxage 7
            missingok
            notifempty
            compress
            delaycompress
          }

    - name: Configure Suricata for lab network monitoring
      copy:
        dest: /etc/suricata/suricata.yaml
        mode: '0644'
        backup: yes
        content: |
          %YAML 1.1
          ---
          vars:
            address-groups:
              HOME_NET: "[{{ lab_network }}]"
              EXTERNAL_NET: "!$HOME_NET"
          
          default-log-dir: /var/log/suricata/
          
          af-packet:
            - interface: eth1
              cluster-id: 99
              cluster-type: cluster_flow
              defrag: yes
          
          outputs:
            - fast:
                enabled: yes
                filename: fast.log
            - eve-log:
                enabled: yes
                filetype: regular
                filename: eve.json
                types:
                  - alert
                  - http
                  - dns
                  - tls
                  - files
                  - flow
          
          logging:
            default-log-level: info

    - name: Enable and start Suricata
      systemd:
        name: suricata
        enabled: yes
        state: started

    - name: Create Guacamole directory
      file:
        path: /opt/guacamole
        state: directory
        mode: '0755'
      when: enable_guacamole

    - name: Ensure Docker service is running (Guacamole)
      systemd:
        name: docker
        enabled: yes
        state: started
      when: enable_guacamole

    - name: Create Guacamole init script directory
      file:
        path: /opt/guacamole/init
        state: directory
        mode: '0755'
      when: enable_guacamole

    - name: Copy Guacamole schema initialization script
      shell: |
        set -e
        docker run --rm guacamole/guacamole:1.5.5 /opt/guacamole/bin/initdb.sh --postgresql > /opt/guacamole/init/schema.sql
      args:
        creates: /opt/guacamole/init/schema.sql
      when: enable_guacamole

    - name: Deploy Guacamole docker-compose file
      copy:
        dest: /opt/guacamole/docker-compose.yml
        mode: '0644'
        content: |
          services:
            postgres:
              image: postgres:15
              container_name: guacamole-postgres
              restart: unless-stopped
              environment:
                POSTGRES_DB: guacamole_db
                POSTGRES_USER: guacamole_user
                POSTGRES_PASSWORD: guacamole_pass
              volumes:
                - guac-postgres:/var/lib/postgresql/data
                - ./init/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
              networks:
                - guacnet

            guacd:
              image: guacamole/guacd:1.5.5
              container_name: guacd
              restart: unless-stopped
              networks:
                - guacnet

            guacamole:
              image: guacamole/guacamole:1.5.5
              container_name: guacamole
              depends_on:
                - guacd
                - postgres
              restart: unless-stopped
              ports:
                - "8082:8080"
              environment:
                GUACD_HOSTNAME: guacd
                GUACD_PORT: 4822
                POSTGRESQL_HOSTNAME: postgres
                POSTGRESQL_PORT: 5432
                POSTGRESQL_DATABASE: guacamole_db
                POSTGRESQL_USER: guacamole_user
                POSTGRESQL_PASSWORD: guacamole_pass
              networks:
                - guacnet

          networks:
            guacnet:
              driver: bridge

          volumes:
            guac-postgres:
              driver: local
      when: enable_guacamole

    - name: Stop Guacamole stack if running
      shell: |
        cd /opt/guacamole && docker-compose down 2>/dev/null || true
      when: enable_guacamole

    - name: Remove Guacamole Postgres volume to force fresh init
      shell: |
        docker volume rm guacamole_guac-postgres 2>/dev/null || true
      when: enable_guacamole

    - name: Start Guacamole stack with schema initialization
      shell: |
        set -e
        cd /opt/guacamole
        docker-compose up -d
        # Wait for postgres to initialize
        sleep 15
      register: guac_up
      when: enable_guacamole

    - name: Mark Guacamole installed
      file:
        path: /opt/guacamole/.installed
        state: touch
      when: enable_guacamole

  handlers:
    - name: Validate nftables configuration
      command: nft -c -f /etc/nftables.conf
      listen: Reload nftables

    - name: Restart nftables service
      systemd:
        name: nftables
        state: restarted
        enabled: yes
      listen: Reload nftables

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
