---
- name: Configure firewall gateway
  hosts: all
  become: yes
  vars:
    # All variables are passed from Vagrantfile/config.yml
    # These defaults allow standalone playbook testing
    wg0_conf: ""
    lab_network: "{{ lab_network | default('10.20.0.0/24') }}"
    firewall_ip: "{{ firewall_ip | default('10.20.0.2') }}"
    openrelik_ip: "{{ openrelik_ip | default('10.20.0.30') }}"
    remnux_ip: "{{ remnux_ip | default('10.20.0.20') }}"
    neko_ip: "{{ neko_ip | default('10.20.0.40') }}"
    host_network_cidr: "{{ host_network_cidr | default('192.168.121.0/24') }}"
    enable_guacamole: "{{ enable_guacamole | default(true) }}"
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install firewall packages
      apt:
        name:
          - curl
          - jq
          - wireguard
          - nftables
          - resolvconf
          - tcpdump
          - tshark
          - suricata
        state: present

    # WireGuard Mullvad (outbound VPN for lab traffic)
    - name: Configure WireGuard Mullvad
      include_tasks: tasks/firewall/wireguard.yml

    # NFTables firewall
    - name: Configure NFTables firewall
      include_tasks: tasks/firewall/nftables.yml

    # Guacamole (RDP/SSH gateway)
    - name: Setup Guacamole
      include_tasks: tasks/firewall/guacamole.yml

    # Network monitoring
    - name: Setup monitoring
      include_tasks: tasks/firewall/monitoring.yml

    # Health checks
    - name: Verify firewall services
      include_tasks: tasks/common/health.yml
      vars:
        health_check_docker: true
