---
- name: Install and configure neko Tor Browser service
  hosts: all
  become: yes
  vars:
    neko_install_dir: "/opt/neko"
    neko_user: "vagrant"
    neko_port: 8080
    neko_broadcast_port: 8081
    neko_chromium_port: 8090
    neko_chromium_broadcast_port: 8091
    
  tasks:
    - name: Set default gateway to firewall (lab network only route)
      shell: |
        ip route del default || true
        ip route add default via {{ lab_gateway }}
      changed_when: false

    - name: Make gateway persistent
      copy:
        dest: /etc/network/if-up.d/lab-gateway
        mode: '0755'
        content: |
          #!/bin/bash
          ip route del default 2>/dev/null || true
          ip route add default via {{ lab_gateway }}

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Wait for Docker daemon to be ready
      wait_for:
        timeout: 15
      when: false  # This just pauses 15 seconds

    - name: Install Docker Compose (standalone binary)
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Create neko directory
      file:
        path: "{{ neko_install_dir }}"
        state: directory
        mode: '0755'

    - name: Create neko config directory
      file:
        path: "{{ neko_install_dir }}/config"
        state: directory
        mode: '0755'

    - name: Create docker-compose.yml for neko
      copy:
        content: |
          version: '3.8'
          
          services:
            neko-tor:
              image: ghcr.io/m1k1o/neko/tor-browser:latest
              container_name: neko-tor-browser
              restart: unless-stopped
              shm_size: 2gb
              ports:
                - "{{ neko_port }}:8080"
                - "{{ neko_broadcast_port }}:8081"
              environment:
                - NEKO_DESKTOP_SCREEN=1920x1080
                - NEKO_MEMBER_PROVIDER=multiuser
                - NEKO_MEMBER_MULTIUSER_USER_PASSWORD={{ neko_password }}
                - NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD={{ neko_admin_password }}
                - NEKO_SERVER_BIND=0.0.0.0:8080
                - NEKO_WEBRTC_BIND=0.0.0.0:8081
                - NEKO_NAT=1
                - NEKO_WEBRTC_EPR=50000-50100
              cap_add:
                - SYS_ADMIN
                - NET_ADMIN
              sysctls:
                - net.ipv4.ip_forward=1
              networks:
                - neko-network

            neko-chromium:
              image: ghcr.io/m1k1o/neko/chromium:latest
              container_name: neko-chromium-browser
              restart: unless-stopped
              shm_size: 2gb
              ports:
                - "{{ neko_chromium_port }}:8080"
                - "{{ neko_chromium_broadcast_port }}:8081"
              environment:
                - NEKO_DESKTOP_SCREEN=1920x1080
                - NEKO_MEMBER_PROVIDER=multiuser
                - NEKO_MEMBER_MULTIUSER_USER_PASSWORD={{ neko_password }}
                - NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD={{ neko_admin_password }}
                - NEKO_SERVER_BIND=0.0.0.0:8080
                - NEKO_WEBRTC_BIND=0.0.0.0:8081
                - NEKO_NAT=1
                - NEKO_WEBRTC_EPR=50101-50200
              cap_add:
                - SYS_ADMIN
                - NET_ADMIN
              sysctls:
                - net.ipv4.ip_forward=1
              networks:
                - neko-network
          
          networks:
            neko-network:
              driver: bridge
        dest: "{{ neko_install_dir }}/docker-compose.yml"

    - name: Create neko systemd service
      copy:
        content: |
          [Unit]
          Description=Neko Tor Browser Service
          After=docker.service
          Requires=docker.service
          
          [Service]
          Type=simple
          WorkingDirectory={{ neko_install_dir }}
          ExecStart=/usr/local/bin/docker-compose -f docker-compose.yml up
          ExecStop=/usr/local/bin/docker-compose -f docker-compose.yml down
          Restart=on-failure
          RestartSec=10
          User=root
          
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/neko.service
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable neko service
      systemd:
        name: neko
        state: started
        enabled: yes

    - name: Wait for neko to be ready
      wait_for:
        port: "{{ neko_port }}"
        delay: 10
        timeout: 120
      retries: 3
      register: neko_wait
      until: neko_wait is succeeded
      ignore_errors: yes

    - name: Check neko service status if startup failed
      shell: |
        systemctl status neko || true
        docker ps || true
        docker logs neko-tor-browser 2>&1 | tail -50 || true
      when: neko_wait is failed
      register: neko_debug

    - name: Display neko startup debug info
      debug:
        var: neko_debug.stdout_lines
      when: neko_wait is failed

    - name: Display neko access information
      debug:
        msg:
          - "=========================================="
          - "Neko Tor Browser Service Started"
          - "=========================================="
          - "Access neko at: http://{{ ansible_default_ipv4.address }}:{{ neko_port }}"
          - "WebRTC broadcast port: {{ neko_broadcast_port }}"
          - "User password: {{ neko_password }}"
          - "Admin password: {{ neko_admin_password }}"
          - "=========================================="
