---
- name: Install and configure Pangolin
  hosts: all
  become: yes
  vars:
    pangolin_enabled: "{{ pangolin_enabled | default(true) }}"
    pangolin_install_dir: "{{ pangolin_install_dir | default('/opt/pangolin') }}"
    pangolin_domain: "{{ pangolin_domain | default('utgard.dig-sec.com') }}"
    pangolin_bind_ip: "{{ (pangolin_bind_ip | default('')) | length > 0 | ternary(pangolin_bind_ip, ansible_default_ipv4.address) }}"
    pangolin_acme_email: "{{ pangolin_acme_email | default('admin@utgard.dig-sec.com') }}"
    pangolin_secret: "{{ pangolin_secret | default('utgard-lab-secret-key-change-me-in-production') }}"

  tasks:
    - name: Configure lab network
      include_tasks: tasks/common/network.yml

    - name: Install Docker
      include_tasks: tasks/common/docker.yml
      when: pangolin_enabled | bool

    - name: Deploy Pangolin
      include_tasks: tasks/pangolin/install.yml
      when: pangolin_enabled | bool
