---
- name: Prepare REMnux analyst VM (scaffold)
  hosts: all
  become: yes
  vars:
    lab_gateway: "10.20.0.1"
    # REMnux CLI currently unsupported on Ubuntu 22.04 (jammy).
    # Set to true only if environment supports remnux-cli.
    remnux_install_cli: false
  tasks:
    - name: Set default gateway to firewall (lab network only route)
      shell: |
        ip route del default || true
        ip route add default via {{ lab_gateway }}
      changed_when: false

    - name: Make gateway persistent
      copy:
        dest: /etc/network/if-up.d/lab-gateway
        mode: '0755'
        content: |
          #!/bin/bash
          ip route del default 2>/dev/null || true
          ip route add default via {{ lab_gateway }}

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base analysis tools
      apt:
        name:
          - curl
          - wget
          - git
          - python3
          - python3-pip
          - yara
          - binwalk
          - tshark
          - bsdextrautils  # provides hexdump on Ubuntu 22.04
          - coreutils
          - file
        state: present

    - name: Download REMnux CLI installer
      get_url:
        url: https://github.com/REMnux/remnux-cli/releases/download/v1.5.1/remnux-cli-linux
        dest: /usr/local/bin/remnux
        mode: '0755'
      register: remnux_cli_download

    - name: Install REMnux distribution (addon mode)
      shell: |
        remnux install --mode=addon --user=vagrant --dev
      environment:
        DEBIAN_FRONTEND: noninteractive
      args:
        creates: /usr/local/remnux-version
      register: remnux_install
      async: 3600
      poll: 30
      ignore_errors: yes
      when: remnux_install_cli

    - name: Display REMnux install result
      debug:
        msg: "{{ remnux_install.stdout_lines | default(['REMnux installation in progress...']) }}"
      when: remnux_install_cli and (remnux_install is defined)

    - name: Install RDP and desktop environment
      apt:
        name:
          - xrdp
          - xfce4
          - xfce4-goodies
        state: present

    - name: Ensure xrdp service is running
      systemd:
        name: xrdp
        state: started
        enabled: yes

    - name: Create .xsession for xfce4
      copy:
        dest: /home/vagrant/.xsession
        owner: vagrant
        group: vagrant
        mode: '0644'
        content: |
          #!/bin/bash
          startxfce4

    - name: Create placeholder for REMnux installer instructions
      copy:
        dest: /usr/local/share/remnux-README.txt
        mode: '0644'
        content: |
          REMnux Distribution Installed
          ------------------------------
          This VM has the full REMnux distribution installed via remnux-cli.
          
          Key tools available:
          - Malware analysis: Ghidra, Radare2, Cutter, Binary Ninja (community)
          - Network: Wireshark, tcpdump, NetworkMiner, Zeek
          - Memory forensics: Volatility 2 & 3
          - File analysis: olevba, pdfid, pdf-parser, rtfdump
          - Reverse engineering: IDA Free, x64dbg (via Wine)
          - Scripting: Python 3, Ruby, Perl with malware analysis libraries
          
          Documentation: https://docs.remnux.org/
          Tool list: https://docs.remnux.org/discover-the-tools/
          
          To update: sudo remnux update
      when: remnux_install_cli

    - name: Show message
      debug:
        msg:
          - "REMnux VM configured with base analysis tools (CLI install disabled)."
          - "Access via Guacamole Web at http://localhost:18080/guacamole/."
          - "User: vagrant / Pass: vagrant"
